Join COPY and RUN instructions

diff --git a/flavors/terraform/Dockerfile b/flavors/terraform/Dockerfile
--- a/flavors/terraform/Dockerfile
+++ b/flavors/terraform/Dockerfile
@@ -148,7 +148,6 @@ ENV PATH="${PATH}":/venvs/ansible-lint/bin:/venvs/djlint/bin:/venvs/semgrep/bin:
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
 
-# Downgrade npm because from npm@v7, npm install crashes when called from root directory within Dockerfile
 ENV NODE_OPTIONS="--max-old-space-size=8192"
 #NPM__START
 WORKDIR /node-deps
@@ -184,8 +183,8 @@ WORKDIR /
 #NPM__END
 
 # Add node packages to path #
-ENV PATH="/node-deps/node_modules/.bin:${PATH}"
-ENV NODE_PATH="/node-deps/node_modules"
+ENV PATH="/node-deps/node_modules/.bin:${PATH}" \
+    NODE_PATH="/node-deps/node_modules"
 
 ##############################
 # Installs ruby dependencies #
@@ -206,15 +205,14 @@ RUN echo 'gem: --no-document' >> ~/.gemrc && \
 #OTHER__START
 # actionlint installation
 ENV GO111MODULE=on
-RUN go install github.com/rhysd/actionlint/cmd/actionlint@v1.6.16
+RUN go install github.com/rhysd/actionlint/cmd/actionlint@v1.6.16 \
 
 # bash-exec installation
-RUN printf '#!/bin/bash \n\nif [[ -x "$1" ]]; then exit 0; else echo "Error: File:[$1] is not executable"; exit 1; fi' > /usr/bin/bash-exec \
-    && chmod +x /usr/bin/bash-exec
-
+    && printf '#!/bin/bash \n\nif [[ -x "$1" ]]; then exit 0; else echo "Error: File:[$1] is not executable"; exit 1; fi' > /usr/bin/bash-exec \
+    && chmod +x /usr/bin/bash-exec \
 
 # shellcheck installation
-RUN ML_THIRD_PARTY_DIR="/third-party/shellcheck" \
+    && ML_THIRD_PARTY_DIR="/third-party/shellcheck" \
     && mkdir -p ${ML_THIRD_PARTY_DIR} \
     && wget -qO- "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" | tar -xJv --directory ${ML_THIRD_PARTY_DIR} \
     && mv "${ML_THIRD_PARTY_DIR}/shellcheck-stable/shellcheck" /usr/bin/ \
@@ -223,95 +221,108 @@ RUN ML_THIRD_PARTY_DIR="/third-party/shellcheck" \
     && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
 
 ENV PATH="/root/.cargo/bin:${PATH}"
-RUN cargo install shellcheck-sarif
+RUN cargo install shellcheck-sarif \
 
 # shfmt installation
-COPY --from=shfmt /bin/shfmt /usr/bin/
+# Managed with COPY --from=shfmt /bin/shfmt /usr/bin/
 
 # hadolint installation
-COPY --from=hadolint /bin/hadolint /usr/bin/hadolint
+# Managed with COPY --from=hadolint /bin/hadolint /usr/bin/hadolint
 
 # editorconfig-checker installation
-COPY --from=editorconfig-checker /usr/bin/ec /usr/bin/editorconfig-checker
+# Managed with COPY --from=editorconfig-checker /usr/bin/ec /usr/bin/editorconfig-checker
 
 # dotenv-linter installation
-RUN wget -q -O - https://raw.githubusercontent.com/dotenv-linter/dotenv-linter/master/install.sh | sh -s
+    && wget -q -O - https://raw.githubusercontent.com/dotenv-linter/dotenv-linter/master/install.sh | sh -s \
 
 # ktlint installation
-RUN curl --retry 5 --retry-delay 5 -sSLO https://github.com/pinterest/ktlint/releases/latest/download/ktlint && \
+    && curl --retry 5 --retry-delay 5 -sSLO https://github.com/pinterest/ktlint/releases/latest/download/ktlint && \
     chmod a+x ktlint && \
-    mv "ktlint" /usr/bin/
-
+    mv "ktlint" /usr/bin/ \
 
 # kubeval installation
-RUN ML_THIRD_PARTY_DIR="/third-party/kubeval" \
+    && ML_THIRD_PARTY_DIR="/third-party/kubeval" \
     && mkdir -p ${ML_THIRD_PARTY_DIR} \
     && wget -P ${ML_THIRD_PARTY_DIR} -q https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz \
     && tar xf ${ML_THIRD_PARTY_DIR}/kubeval-linux-amd64.tar.gz --directory ${ML_THIRD_PARTY_DIR} \
     && mv ${ML_THIRD_PARTY_DIR}/kubeval /usr/local/bin \
-    && find ${ML_THIRD_PARTY_DIR} -type f -not -name 'LICENSE*' -delete -o -type d -empty -delete
-
+    && find ${ML_THIRD_PARTY_DIR} -type f -not -name 'LICENSE*' -delete -o -type d -empty -delete \
 
 # kubeconform installation
-RUN ML_THIRD_PARTY_DIR="/third-party/kubeconform" \
+    && ML_THIRD_PARTY_DIR="/third-party/kubeconform" \
     && KUBECONFORM_VERSION=v0.4.12 \
     && mkdir -p ${ML_THIRD_PARTY_DIR} \
     && wget -P ${ML_THIRD_PARTY_DIR} -q https://github.com/yannh/kubeconform/releases/download/$KUBECONFORM_VERSION/kubeconform-linux-amd64.tar.gz \
     && tar xf ${ML_THIRD_PARTY_DIR}/kubeconform-linux-amd64.tar.gz --directory ${ML_THIRD_PARTY_DIR} \
     && mv ${ML_THIRD_PARTY_DIR}/kubeconform /usr/local/bin \
-    && find ${ML_THIRD_PARTY_DIR} -type f -not -name 'LICENSE*' -delete -o -type d -empty -delete
-
+    && find ${ML_THIRD_PARTY_DIR} -type f -not -name 'LICENSE*' -delete -o -type d -empty -delete \
 
 # protolint installation
-COPY --from=protolint /usr/local/bin/protolint /usr/bin/
+# Managed with COPY --from=protolint /usr/local/bin/protolint /usr/bin/
 
 # checkov installation
-RUN pip3 install --upgrade --no-cache-dir pip && pip3 install --upgrade --no-cache-dir setuptools \
-    && pip3 install --no-cache-dir checkov
-
+    && pip3 install --upgrade --no-cache-dir pip && pip3 install --upgrade --no-cache-dir setuptools \
+    && pip3 install --no-cache-dir checkov \
 
 # gitleaks installation
-COPY --from=gitleaks /usr/bin/gitleaks /usr/bin/
+# Managed with COPY --from=gitleaks /usr/bin/gitleaks /usr/bin/
 
 # trivy installation
-RUN wget --tries=5 -q -O - https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.29.2 && \
+    && wget --tries=5 -q -O - https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.29.2 && \
     wget --tries=5 -q -O /usr/local/bin/sarif.tpl https://raw.githubusercontent.com/aquasecurity/trivy/714b5ca2460363e082d42a8d933c7a0cb7eff7a8/contrib/sarif.tpl && \
-    chmod 644 /usr/local/bin/sarif.tpl
-
+    chmod 644 /usr/local/bin/sarif.tpl \
 
 # misspell installation
-RUN ML_THIRD_PARTY_DIR="/third-party/misspell" \
+    && ML_THIRD_PARTY_DIR="/third-party/misspell" \
     && mkdir -p ${ML_THIRD_PARTY_DIR} \
     && curl -L -o ${ML_THIRD_PARTY_DIR}/install-misspell.sh https://git.io/misspell \
     && sh .${ML_THIRD_PARTY_DIR}/install-misspell.sh \
     && find ${ML_THIRD_PARTY_DIR} -type f -not -name 'LICENSE*' -delete -o -type d -empty -delete \
-    && find /tmp -path '/tmp/tmp.*' -type f -name 'misspell*' -delete -o -type d -empty -delete
-
+    && find /tmp -path '/tmp/tmp.*' -type f -name 'misspell*' -delete -o -type d -empty -delete \
 
 # tflint installation
-COPY --from=tflint /usr/local/bin/tflint /usr/bin/
+# Managed with COPY --from=tflint /usr/local/bin/tflint /usr/bin/
 
 # terrascan installation
-COPY --from=terrascan /go/bin/terrascan /usr/bin/
+# Managed with COPY --from=terrascan /go/bin/terrascan /usr/bin/
 
 # terragrunt installation
-COPY --from=terragrunt /usr/local/bin/terragrunt /usr/bin/
+# Managed with COPY --from=terragrunt /usr/local/bin/terragrunt /usr/bin/
 
 # terraform-fmt installation
-COPY --from=terragrunt /bin/terraform /usr/bin/
+# Managed with COPY --from=terragrunt /bin/terraform /usr/bin/
 
 # checkov installation
-# Next line commented because already managed by another linter
-# RUN pip3 install --upgrade --no-cache-dir pip && pip3 install --upgrade --no-cache-dir setuptools \
-#     && pip3 install --no-cache-dir checkov
+    && pip3 install --upgrade --no-cache-dir pip && pip3 install --upgrade --no-cache-dir setuptools \
+    && pip3 install --no-cache-dir checkov \
 
 # kics installation
-COPY --from=kics /app/bin/kics /usr/bin/
-RUN mkdir -p /opt/kics/assets
+# Managed with COPY --from=kics /app/bin/kics /usr/bin/
+    && mkdir -p /opt/kics/assets
 ENV KICS_QUERIES_PATH=/opt/kics/assets/queries KICS_LIBRARIES_PATH=/opt/kics/assets/libraries
-COPY --from=kics /app/bin/assets /opt/kics/assets/
+# Managed with COPY --from=kics /app/bin/assets /opt/kics/assets/
 
 #OTHER__END
+
+##############################
+# COPY instructions #
+#############################################################################################
+## @generated by .automation/build.py using descriptor files, please do not update manually ##
+#############################################################################################
+
+#COPY__START
+COPY --from=shfmt /bin/shfmt /usr/bin/
+COPY --from=hadolint /bin/hadolint /usr/bin/hadolint
+COPY --from=editorconfig-checker /usr/bin/ec /usr/bin/editorconfig-checker
+COPY --from=protolint /usr/local/bin/protolint /usr/bin/
+COPY --from=gitleaks /usr/bin/gitleaks /usr/bin/
+COPY --from=tflint /usr/local/bin/tflint /usr/bin/
+COPY --from=terrascan /go/bin/terrascan /usr/bin/
+COPY --from=terragrunt /usr/local/bin/terragrunt /usr/bin/
+COPY --from=terragrunt /bin/terraform /usr/bin/
+COPY --from=kics /app/bin/kics /usr/bin/
+COPY --from=kics /app/bin/assets /opt/kics/assets/
+#COPY__END
 
 ################################
 # Installs python dependencies #
