Improve build performances and docker image size (#1857)
* apk packages in one call

* build

* Use DOCKER_BUILDKIT=1

* fix Dockerfile

* Join COPY and RUN instructions

* Fix typo in python

* Disable pyright

* changelog

* cspell

* cd / when necessary

* typo

* Move COPY block

* Fix duplicates

diff --git a/flavors/dotnet/Dockerfile b/flavors/dotnet/Dockerfile
--- a/flavors/dotnet/Dockerfile
+++ b/flavors/dotnet/Dockerfile
@@ -42,27 +42,24 @@ ARG PSSA_VERSION='latest'
 
 WORKDIR /
 
-# APK Packages used by mega-linter core architecture
-RUN apk add --update --no-cache \
-        bash \
-        ca-certificates \
-        curl \
-        gcc \
-        git \
-        libffi-dev \
-        make \
-        musl-dev \
-        openssh && \
-    git config --global core.autocrlf true
-
 #############################################################################################
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
 #APK__START
 RUN apk add --update --no-cache \
+                bash \
+                ca-certificates \
+                curl \
+                gcc \
+                git \
+                libffi-dev \
+                make \
+                musl-dev \
+                openssh \
+                docker \
+                openrc \
                 go \
                 icu-libs \
-                bash \
                 libcurl \
                 libintl \
                 libssl1.1 \
@@ -71,19 +68,65 @@ RUN apk add --update --no-cache \
                 zlib \
                 zlib-dev \
                 openjdk11 \
+                perl \
+                perl-dev \
+                gnupg \
+                php7 \
+                php7-phar \
+                php7-json \
+                php7-mbstring \
+                php7-xmlwriter \
+                php7-tokenizer \
+                php7-ctype \
+                php7-curl \
+                php7-dom \
+                php7-simplexml \
+                php8 \
+                php8-phar \
+                php8-mbstring \
+                php8-xmlwriter \
+                php8-tokenizer \
+                php8-ctype \
+                php8-curl \
+                php8-dom \
+                php8-simplexml \
+                composer \
+                dpkg \
                 nodejs \
                 npm \
                 yarn \
+                openssl \
+                readline-dev \
+                g++ \
                 libc-dev \
+                libgcc \
                 libxml2-dev \
                 libxml2-utils \
-                libgcc \
+                linux-headers \
+                R \
+                R-dev \
+                R-doc \
                 nodejs-current \
                 ruby \
                 ruby-dev \
                 ruby-bundler \
-                ruby-rdoc
+                ruby-rdoc \
+    && git config --global core.autocrlf true
 #APK__END
+
+##############################
+# COPY instructions #
+#############################################################################################
+## @generated by .automation/build.py using descriptor files, please do not update manually ##
+#############################################################################################
+
+#COPY__START
+COPY --from=shfmt /bin/shfmt /usr/bin/
+COPY --from=hadolint /bin/hadolint /usr/bin/hadolint
+COPY --from=editorconfig-checker /usr/bin/ec /usr/bin/editorconfig-checker
+COPY --from=protolint /usr/local/bin/protolint /usr/bin/
+COPY --from=gitleaks /usr/bin/gitleaks /usr/bin/
+#COPY__END
 
 # PATH for golang
 ENV GOROOT=/usr/lib/go \
@@ -121,7 +164,6 @@ ENV PATH="${PATH}":/venvs/ansible-lint/bin:/venvs/cpplint/bin:/venvs/djlint/bin:
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
 
-# Downgrade npm because from npm@v7, npm install crashes when called from root directory within Dockerfile
 ENV NODE_OPTIONS="--max-old-space-size=8192"
 #NPM__START
 WORKDIR /node-deps
@@ -158,8 +200,8 @@ WORKDIR /
 #NPM__END
 
 # Add node packages to path #
-ENV PATH="/node-deps/node_modules/.bin:${PATH}"
-ENV NODE_PATH="/node-deps/node_modules"
+ENV PATH="/node-deps/node_modules/.bin:${PATH}" \
+    NODE_PATH="/node-deps/node_modules"
 
 ##############################
 # Installs ruby dependencies #
@@ -186,11 +228,10 @@ RUN mkdir -p ${PWSH_DIRECTORY} \
         | cut -d '"' -f 4 \
         | xargs -n 1 wget -O - \
         | tar -xzC ${PWSH_DIRECTORY} \
-    && ln -sf ${PWSH_DIRECTORY}/pwsh /usr/bin/pwsh
-
+    && ln -sf ${PWSH_DIRECTORY}/pwsh /usr/bin/pwsh \
 
 # CSHARP installation
-RUN wget --tries=5 -q -O dotnet-install.sh https://dot.net/v1/dotnet-install.sh \
+    && wget --tries=5 -q -O dotnet-install.sh https://dot.net/v1/dotnet-install.sh \
     && chmod +x dotnet-install.sh \
     && ./dotnet-install.sh --install-dir /usr/share/dotnet -channel 5.0 -version latest
 
@@ -225,16 +266,14 @@ RUN curl --retry 5 --retry-delay 5 -sLO "${ARM_TTK_URI}" \
     && unzip "${ARM_TTK_NAME}" -d "${ARM_TTK_DIRECTORY}" \
     && rm "${ARM_TTK_NAME}" \
     && ln -sTf "${ARM_TTK_PSD1}" /usr/bin/arm-ttk \
-    && chmod a+x /usr/bin/arm-ttk
-
+    && chmod a+x /usr/bin/arm-ttk \
 
 # bash-exec installation
-RUN printf '#!/bin/bash \n\nif [[ -x "$1" ]]; then exit 0; else echo "Error: File:[$1] is not executable"; exit 1; fi' > /usr/bin/bash-exec \
-    && chmod +x /usr/bin/bash-exec
-
+    && printf '#!/bin/bash \n\nif [[ -x "$1" ]]; then exit 0; else echo "Error: File:[$1] is not executable"; exit 1; fi' > /usr/bin/bash-exec \
+    && chmod +x /usr/bin/bash-exec \
 
 # shellcheck installation
-RUN ML_THIRD_PARTY_DIR="/third-party/shellcheck" \
+    && ML_THIRD_PARTY_DIR="/third-party/shellcheck" \
     && mkdir -p ${ML_THIRD_PARTY_DIR} \
     && wget -qO- "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" | tar -xJv --directory ${ML_THIRD_PARTY_DIR} \
     && mv "${ML_THIRD_PARTY_DIR}/shellcheck-stable/shellcheck" /usr/bin/ \
@@ -243,82 +282,75 @@ RUN ML_THIRD_PARTY_DIR="/third-party/shellcheck" \
     && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
 
 ENV PATH="/root/.cargo/bin:${PATH}"
-RUN cargo install shellcheck-sarif
+RUN cargo install shellcheck-sarif \
 
 # shfmt installation
-COPY --from=shfmt /bin/shfmt /usr/bin/
+# Managed with COPY --from=shfmt /bin/shfmt /usr/bin/
 
 # dotnet-format installation
-RUN /usr/share/dotnet/dotnet tool install -g dotnet-format
+    && /usr/share/dotnet/dotnet tool install -g dotnet-format \
 
 # hadolint installation
-COPY --from=hadolint /bin/hadolint /usr/bin/hadolint
+# Managed with COPY --from=hadolint /bin/hadolint /usr/bin/hadolint
 
 # editorconfig-checker installation
-COPY --from=editorconfig-checker /usr/bin/ec /usr/bin/editorconfig-checker
+# Managed with COPY --from=editorconfig-checker /usr/bin/ec /usr/bin/editorconfig-checker
 
 # dotenv-linter installation
-RUN wget -q -O - https://raw.githubusercontent.com/dotenv-linter/dotenv-linter/master/install.sh | sh -s
+    && wget -q -O - https://raw.githubusercontent.com/dotenv-linter/dotenv-linter/master/install.sh | sh -s \
 
 # ktlint installation
-RUN curl --retry 5 --retry-delay 5 -sSLO https://github.com/pinterest/ktlint/releases/latest/download/ktlint && \
+    && curl --retry 5 --retry-delay 5 -sSLO https://github.com/pinterest/ktlint/releases/latest/download/ktlint && \
     chmod a+x ktlint && \
-    mv "ktlint" /usr/bin/
-
+    mv "ktlint" /usr/bin/ \
 
 # kubeval installation
-RUN ML_THIRD_PARTY_DIR="/third-party/kubeval" \
+    && ML_THIRD_PARTY_DIR="/third-party/kubeval" \
     && mkdir -p ${ML_THIRD_PARTY_DIR} \
     && wget -P ${ML_THIRD_PARTY_DIR} -q https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz \
     && tar xf ${ML_THIRD_PARTY_DIR}/kubeval-linux-amd64.tar.gz --directory ${ML_THIRD_PARTY_DIR} \
     && mv ${ML_THIRD_PARTY_DIR}/kubeval /usr/local/bin \
-    && find ${ML_THIRD_PARTY_DIR} -type f -not -name 'LICENSE*' -delete -o -type d -empty -delete
-
+    && find ${ML_THIRD_PARTY_DIR} -type f -not -name 'LICENSE*' -delete -o -type d -empty -delete \
 
 # kubeconform installation
-RUN ML_THIRD_PARTY_DIR="/third-party/kubeconform" \
+    && ML_THIRD_PARTY_DIR="/third-party/kubeconform" \
     && KUBECONFORM_VERSION=v0.4.12 \
     && mkdir -p ${ML_THIRD_PARTY_DIR} \
     && wget -P ${ML_THIRD_PARTY_DIR} -q https://github.com/yannh/kubeconform/releases/download/$KUBECONFORM_VERSION/kubeconform-linux-amd64.tar.gz \
     && tar xf ${ML_THIRD_PARTY_DIR}/kubeconform-linux-amd64.tar.gz --directory ${ML_THIRD_PARTY_DIR} \
     && mv ${ML_THIRD_PARTY_DIR}/kubeconform /usr/local/bin \
-    && find ${ML_THIRD_PARTY_DIR} -type f -not -name 'LICENSE*' -delete -o -type d -empty -delete
-
+    && find ${ML_THIRD_PARTY_DIR} -type f -not -name 'LICENSE*' -delete -o -type d -empty -delete \
 
 # checkmake installation
-RUN ( [ -d /usr/local/bin ] || mkdir -p /usr/local/bin ) \
+    && ( [ -d /usr/local/bin ] || mkdir -p /usr/local/bin ) \
     && wget -q "https://github.com/mrtazz/checkmake/releases/download/0.2.1/checkmake-0.2.1.linux.amd64" -O /usr/local/bin/checkmake \
-    && chmod 755 /usr/local/bin/checkmake
-
+    && chmod 755 /usr/local/bin/checkmake \
 
 # powershell installation
-RUN pwsh -c 'Install-Module -Name PSScriptAnalyzer -RequiredVersion ${PSSA_VERSION} -Scope AllUsers -Force'
+    && pwsh -c 'Install-Module -Name PSScriptAnalyzer -RequiredVersion ${PSSA_VERSION} -Scope AllUsers -Force' \
 
 # protolint installation
-COPY --from=protolint /usr/local/bin/protolint /usr/bin/
+# Managed with COPY --from=protolint /usr/local/bin/protolint /usr/bin/
 
 # checkov installation
-RUN pip3 install --upgrade --no-cache-dir pip && pip3 install --upgrade --no-cache-dir setuptools \
-    && pip3 install --no-cache-dir checkov
-
+    && pip3 install --upgrade --no-cache-dir pip && pip3 install --upgrade --no-cache-dir setuptools \
+    && pip3 install --no-cache-dir checkov \
 
 # gitleaks installation
-COPY --from=gitleaks /usr/bin/gitleaks /usr/bin/
+# Managed with COPY --from=gitleaks /usr/bin/gitleaks /usr/bin/
 
 # trivy installation
-RUN wget --tries=5 -q -O - https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.29.2 && \
+    && wget --tries=5 -q -O - https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.29.2 && \
     wget --tries=5 -q -O /usr/local/bin/sarif.tpl https://raw.githubusercontent.com/aquasecurity/trivy/714b5ca2460363e082d42a8d933c7a0cb7eff7a8/contrib/sarif.tpl && \
-    chmod 644 /usr/local/bin/sarif.tpl
-
+    chmod 644 /usr/local/bin/sarif.tpl \
 
 # misspell installation
-RUN ML_THIRD_PARTY_DIR="/third-party/misspell" \
+    && ML_THIRD_PARTY_DIR="/third-party/misspell" \
     && mkdir -p ${ML_THIRD_PARTY_DIR} \
     && curl -L -o ${ML_THIRD_PARTY_DIR}/install-misspell.sh https://git.io/misspell \
     && sh .${ML_THIRD_PARTY_DIR}/install-misspell.sh \
     && find ${ML_THIRD_PARTY_DIR} -type f -not -name 'LICENSE*' -delete -o -type d -empty -delete \
-    && find /tmp -path '/tmp/tmp.*' -type f -name 'misspell*' -delete -o -type d -empty -delete
-
+    && find /tmp -path '/tmp/tmp.*' -type f -name 'misspell*' -delete -o -type d -empty -delete \
 
 # tsqllint installation
 # Next line commented because already managed by another linter
@@ -327,7 +359,7 @@ RUN ML_THIRD_PARTY_DIR="/third-party/misspell" \
 #     && ./dotnet-install.sh --install-dir /usr/share/dotnet -channel 5.0 -version latest
 # Next line commented because already managed by another linter
 # ENV PATH="${PATH}:/root/.dotnet/tools:/usr/share/dotnet"
-RUN dotnet tool install --global --version 1.14.5 TSQLLint
+    && dotnet tool install --global --version 1.14.5 TSQLLint
 
 # dotnet-format installation
 # Next line commented because already managed by another linter
