V6/docker standalone linters (#1099)
* Build unique linters dockerfiles

* Dockerfiles for unique linters + Improve perfs

* CI to build standalone images

* Fix CI

* Matrix jobs: do not fail other jobs if one fails

* Manage docker build --squash

* Add test cases to "only" docker images

* No codecov call when not running all tests

* Create output sarif folder when SARIF is from stdout

* Remove useless python packages for ML runtime

* Remove pytest-cov pytest-timeout from runtime image

* Optimize Until dotenv linter

* gcc in all dockerfiles + go for actionlint

* Add libffi-dev in all Docker images

* Add make

* add bash

* add musl-dev

* Fix linters install

* gnugpg for php

* Automate node & ruby-dev installation if packages are used in install

* Fix dotnet install

* More preset variables on single-linter docker images

* typo

* typo2

* Add ruby-bundler for gem packages

* Remove PHP_BUILTIN as it has been replaced by PHP_PHPLINT

* Fix descriptors and test class

* Improve CI perfs for only-linters build

* More fixes

* Fix kotlin install

* Fix raku install

* Fix R

* Fix scala

* Fix TSX

* Fix Vb .NET

* Build

* Linters page

* rollback raku

* Fix terraform_fmt & rollback raku

* Try fix rakudo

* Fix duplicate ARG and FROM in dockerfile

* Fix python lint err

* Disable lint_all_other_linters_files=true if in SINGLE_LINTER mode

* lint fix

* Reduce docker layers

* Reduce again the list of docker build steps

* Do not keep text logs if not wanted + linter delete SARIF files

* Fix CI

* Fix SARIF test case

diff --git a/flavors/dotnet/Dockerfile b/flavors/dotnet/Dockerfile
--- a/flavors/dotnet/Dockerfile
+++ b/flavors/dotnet/Dockerfile
@@ -39,55 +39,52 @@ ARG PSSA_VERSION='latest'
 
 # APK Packages used by mega-linter core architecture
 RUN apk add --update --no-cache \
-    bash \
-    coreutils \
-    curl \
-    file \
-    gcc \
-    git git-lfs\
-    go \
-    gnupg \
-    icu-libs \
-    krb5-libs \
-    libcurl libintl libssl1.1 libstdc++ \
-    libffi-dev \
-    linux-headers \
-    make \
-    musl-dev \
-    openjdk8 \
-    openssh \
-    npm \
-    nodejs \
-    py3-setuptools \
-    readline-dev \
-    ruby-bundler \
-    ruby-dev \
-    yarn
-
-RUN git config --global core.autocrlf true
+        bash \
+        curl \
+        gcc \
+        git \
+        libffi-dev \
+        make \
+        musl-dev && \
+    git config --global core.autocrlf true
 
 #############################################################################################
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
 #APK__START
 RUN apk add --update --no-cache \
+                go \
+                icu-libs \
+                bash \
+                libcurl \
+                libintl \
+                libssl1.1 \
+                libstdc++ \
                 lttng-ust-dev \
                 zlib \
                 zlib-dev \
+                openjdk8 \
+                nodejs \
+                npm \
+                yarn \
                 libc-dev \
                 libxml2-dev \
                 libxml2-utils \
-                libgcc
+                libgcc \
+                ruby \
+                ruby-dev \
+                ruby-bundler \
+                ruby-rdoc
 #APK__END
 
-# Ignore npm package issues
-RUN yarn config set ignore-engines true
 # PATH for golang
-ENV GOROOT=/usr/lib/go
-ENV GOPATH=/go
+ENV GOROOT=/usr/lib/go \
+    GOPATH=/go
 # hadolint ignore=DL3044
 ENV PATH="$PATH":"$GOROOT"/bin:"$GOPATH"/bin
-RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin
+RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin || true && \
+    # Ignore npm package issues
+    yarn config set ignore-engines true || true
 
 #############################################################################################
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
@@ -110,9 +107,10 @@ RUN pip3 install --no-cache-dir --upgrade \
 #############################################################################################
 
 # Downgrade npm because from npm@v7, npm install crashes when called from root directory within Dockerfile
-RUN npm install npm@latest-6 -g
-# Disable package-lock.json to avoid sudden crash. Try to remove later if possible
-RUN echo 'package-lock=false' >> .npmrc 
+RUN npm install npm@latest-6 -g || true && \
+    # Disable package-lock.json to avoid sudden crash. Try to remove later if possible
+    echo 'package-lock=false' >> .npmrc || true
+
 #NPM__START
 RUN npm install --no-cache --ignore-scripts \
                 jscpd@3.3.26 \
@@ -163,14 +161,7 @@ RUN echo 'gem: --no-document' >> ~/.gemrc && \
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
 #OTHER__START
-# CSHARP installation
-RUN wget --tries=5 -q -O dotnet-install.sh https://dot.net/v1/dotnet-install.sh \
-    && chmod +x dotnet-install.sh \
-    && ./dotnet-install.sh --install-dir /usr/share/dotnet -channel 5.0 -version latest
-
-ENV PATH="${PATH}:/root/.dotnet/tools:/usr/share/dotnet"
-
-# POWERSHELL installation
+# ARM installation
 RUN mkdir -p ${PWSH_DIRECTORY} \
     && curl --retry 5 --retry-delay 5 -s https://api.github.com/repos/powershell/powershell/releases/${PWSH_VERSION} \
         | grep browser_download_url \
@@ -181,8 +172,31 @@ RUN mkdir -p ${PWSH_DIRECTORY} \
     && ln -sf ${PWSH_DIRECTORY}/pwsh /usr/bin/pwsh
 
 
-# REPOSITORY installation
-RUN git config --global core.autocrlf true
+# CSHARP installation
+RUN wget --tries=5 -q -O dotnet-install.sh https://dot.net/v1/dotnet-install.sh \
+    && chmod +x dotnet-install.sh \
+    && ./dotnet-install.sh --install-dir /usr/share/dotnet -channel 5.0 -version latest
+
+ENV PATH="${PATH}:/root/.dotnet/tools:/usr/share/dotnet"
+
+# POWERSHELL installation
+# Next line commented because already managed by another linter
+# RUN mkdir -p ${PWSH_DIRECTORY} \
+#     && curl --retry 5 --retry-delay 5 -s https://api.github.com/repos/powershell/powershell/releases/${PWSH_VERSION} \
+#         | grep browser_download_url \
+#         | grep linux-alpine-x64 \
+#         | cut -d '"' -f 4 \
+#         | xargs -n 1 wget -O - \
+#         | tar -xzC ${PWSH_DIRECTORY} \
+#     && ln -sf ${PWSH_DIRECTORY}/pwsh /usr/bin/pwsh
+
+# VBDOTNET installation
+# Next line commented because already managed by another linter
+# RUN wget --tries=5 -q -O dotnet-install.sh https://dot.net/v1/dotnet-install.sh \
+#     && chmod +x dotnet-install.sh \
+#     && ./dotnet-install.sh --install-dir /usr/share/dotnet -channel 5.0 -version latest
+# Next line commented because already managed by another linter
+# ENV PATH="${PATH}:/root/.dotnet/tools:/usr/share/dotnet"
 
 # actionlint installation
 ENV GO111MODULE=on
@@ -209,7 +223,8 @@ RUN wget -qO- "https://github.com/koalaman/shellcheck/releases/download/stable/s
 
 
 # shfmt installation
-ENV GO111MODULE=on
+# Next line commented because already managed by another linter
+# ENV GO111MODULE=on
 RUN go get mvdan.cc/sh/v3/cmd/shfmt@v3.3.1
 
 # dotnet-format installation
@@ -251,7 +266,17 @@ RUN curl -L -o ./install-misspell.sh https://git.io/misspell \
 
 
 # tsqllint installation
+# Next line commented because already managed by another linter
+# RUN wget --tries=5 -q -O dotnet-install.sh https://dot.net/v1/dotnet-install.sh \
+#     && chmod +x dotnet-install.sh \
+#     && ./dotnet-install.sh --install-dir /usr/share/dotnet -channel 5.0 -version latest
+# Next line commented because already managed by another linter
+# ENV PATH="${PATH}:/root/.dotnet/tools:/usr/share/dotnet"
 RUN dotnet tool install --global TSQLLint
+
+# dotnet-format installation
+# Next line commented because already managed by another linter
+# RUN /usr/share/dotnet/dotnet tool install -g dotnet-format
 
 #OTHER__END
 
@@ -293,6 +318,10 @@ ENV BUILD_DATE=$BUILD_DATE \
 #FLAVOR__START
 ENV MEGALINTER_FLAVOR=dotnet
 #FLAVOR__END
+
+#EXTRA_DOCKERFILE_LINES__START
+
+#EXTRA_DOCKERFILE_LINES__END
 
 #########################################
 # Label the instance and set maintainer #
