Pull in dockerfile changes lost in rebase

diff --git a/flavors/python/Dockerfile b/flavors/python/Dockerfile
--- a/flavors/python/Dockerfile
+++ b/flavors/python/Dockerfile
@@ -40,87 +40,196 @@ FROM jdkato/vale:latest as vale
 FROM lycheeverse/lychee:latest-alpine as lychee
 #FROM__END
 
-##################
-# Get base image #
-##################
-# https://stackoverflow.com/a/73711302/699056
-FROM multiarch/qemu-user-static:x86_64-aarch64 as qemu
-
-FROM python:3.11.4-alpine3.17
-ARG GITHUB_TOKEN
-
-# https://stackoverflow.com/a/73711302/699056
-COPY --from=qemu /usr/bin/qemu-aarch64-static /usr/bin/
-# https://stackoverflow.com/a/73711302/699056
-RUN apk add --update --no-cache libc6-compat \
-                     gcompat \
-                     qemu-x86_64
+FROM --platform=$BUILDPLATFORM python:3.11.3-alpine3.17 AS build-platform
 
 #############################################################################################
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
-#ARG__START
+#BUILD_PLATFORM_APK__START
 
-#ARG__END
+#BUILD_PLATFORM_APK__END
 
-####################
-# Run APK installs #
-####################
+#BUILD_PLATFORM_OTHER__START
+# bash-exec installation
+RUN printf '#!/bin/bash \n\nif [[ -x "$1" ]]; then exit 0; else echo "Error: File:[$1] is not executable"; exit 1; fi' > /usr/bin/bash-exec \
+    && chmod +x /usr/bin/bash-exec
 
+#
+#BUILD_PLATFORM_OTHER__END
+
+FROM --platform=$BUILDPLATFORM python:3.11.3-alpine3.17 AS node_modules
+
+#NPM_APK__START
+RUN apk add --update --no-cache \
+                npm
+#NPM_APK__END
+
+############################
+# Install NPM dependencies #
+#############################################################################################
+## @generated by .automation/build.py using descriptor files, please do not update manually ##
+#############################################################################################
+
+ENV NODE_OPTIONS="--max-old-space-size=8192" \
+    NODE_ENV=production
+#NPM__START
+WORKDIR /node-deps
+RUN npm --no-cache install --ignore-scripts --omit=dev \
+                jscpd \
+                stylelint \
+                stylelint-config-standard \
+                stylelint-config-sass-guidelines \
+                stylelint-scss \
+                graphql \
+                graphql-schema-linter \
+                npm-groovy-lint \
+                htmlhint \
+                @prantlf/jsonlint \
+                eslint \
+                eslint-plugin-jsonc \
+                @microsoft/eslint-formatter-sarif \
+                v8r \
+                prettier \
+                markdownlint-cli \
+                markdown-link-check \
+                markdown-table-formatter \
+                @stoplight/spectral-cli \
+                secretlint \
+                @secretlint/secretlint-rule-preset-recommend \
+                @secretlint/secretlint-formatter-sarif \
+                cspell \
+                sql-lint \
+                tekton-lint  && \
+    echo "Cleaning npm cache…" \
+    && npm cache clean --force || true \
+    && echo "Changing owner of node_modules files…" \
+    && chown -R "$(id -u)":"$(id -g)" node_modules # fix for https://github.com/npm/cli/issues/5900 \
+    && echo "Removing extra node_module files…" \
+    && rm -rf /root/.npm/_cacache \
+    && find . -name "*.d.ts" -delete \
+    && find . -name "*.map" -delete \
+    && find . -name "*.npmignore" -delete \
+    && find . -name "*.travis.yml" -delete \
+    && find . -name "CHANGELOG.md" -delete \
+    && find . -name "README.md" -delete \
+    && find . -name ".package-lock.json" -delete \
+    && find . -name "package-lock.json" -delete \
+    && find . -name "README.md" -delete
 WORKDIR /
 
+#NPM__END
+
+FROM busybox AS copy-collector
+
+##############################
+# COPY instructions #
 #############################################################################################
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
-#APK__START
-RUN apk add --no-cache \
-                bash \
-                ca-certificates \
-                curl \
+
+#COPY__START
+COPY --link --from=actionlint /usr/local/bin/actionlint /usr/bin/actionlint
+# shellcheck is a dependency for actionlint
+
+COPY --link --from=shellcheck /bin/shellcheck /usr/bin/shellcheck
+COPY --link --from=build-platform /usr/bin/bash-exec /usr/bin/bash-exec
+# Next COPY line commented because already managed by another linter
+# COPY --link --from=shellcheck /bin/shellcheck /usr/bin/shellcheck
+COPY --link --from=shfmt /bin/shfmt /usr/bin/
+COPY --link --from=node_modules /node-deps /node-deps
+COPY --link --from=hadolint /bin/hadolint /usr/bin/hadolint
+COPY --link --from=editorconfig-checker /usr/bin/ec /usr/bin/editorconfig-checker
+COPY --link --from=dotenvlinter /dotenv-linter /usr/bin/dotenv-linter
+COPY --link --from=kubeconform /kubeconform /usr/bin/
+COPY --link --from=checkmake /checkmake /usr/bin/checkmake
+COPY --link --from=protolint /usr/local/bin/protolint /usr/bin/
+COPY --link --from=fetch-ruff /ruff /usr/bin/ruff
+COPY --link --from=gitleaks /usr/bin/gitleaks /usr/bin/
+COPY --link --from=trufflehog /usr/bin/trufflehog /usr/bin/
+COPY --link --from=vale /bin/vale /bin/vale
+COPY --link --from=lychee /usr/local/bin/lychee /usr/bin/
+#COPY__END
+
+#######################################
+# Copy scripts and rules to container #
+#######################################
+COPY --link megalinter/descriptors /megalinter-descriptors
+COPY --link TEMPLATES /action/lib/.automation
+
+FROM --platform=$TARGETPLATFORM python:3.11.3-alpine3.17 AS target-python
+FROM --platform=$BUILDPLATFORM python:3.11.3-alpine3.17 AS python-venv
+
+
+#############################################################################################
+## @generated by .automation/build.py using descriptor files, please do not update manually ##
+#############################################################################################
+
+#PIPVENV_BUILDDEPS__START
+RUN apk add --update --no-cache \
                 gcc \
-                git \
-                git-lfs \
                 libffi-dev \
-                make \
                 musl-dev \
-                openssh \
-                openjdk11 \
-                py3-pyflakes \
-                nodejs \
-                npm \
-                yarn \
-                helm \
-                gcompat \
-                libc6-compat \
-                libstdc++ \
-                libc-dev \
-                libxml2-dev \
-                libxml2-utils \
-                libgcc \
-                nodejs-current \
-                ruby \
-                ruby-dev \
-                ruby-bundler \
-                ruby-rdoc \
-    && git config --global core.autocrlf true
-#APK__END
+                make \
+                curl \
+                openssl-dev \
+                g++ \
+                cmake
+#PIPVENV_BUILDDEPS__END
 
-# PATH for golang & python
-ENV GOROOT=/usr/lib/go \
-    GOPATH=/go
-    # PYTHONPYCACHEPREFIX="$HOME/.cache/cpython/" NV: not working for all packages :/
-# hadolint ignore=DL3044
-ENV PATH="$PATH":"$GOROOT"/bin:"$GOPATH"/bin
-RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin || true && \
-    # Ignore npm package issues
-    yarn config set ignore-engines true || true
+#PIPVENV_DOWNLOAD__START
+RUN --mount=type=cache,id=pip,sharing=locked,target=/var/cache/pip,uid=0 \
+    mkdir /download \
+    && PYTHONDONTWRITEBYTECODE=1 pip3 --disable-pip-version-check install --cache-dir=/var/cache/pip --upgrade pip crossenv \
+&& pip download --cache-dir=/var/cache/pip --dest "/download" \
+      ansible-lint \
+      djlint \
+      pylint \
+      typing-extensions \
+      black \
+      flake8 \
+      isort \
+      black \
+      bandit \
+      bandit_sarif_formatter \
+      bandit[toml] \
+      mypy \
+      pyright \
+      packaging \
+      checkov \
+      semgrep \
+      restructuredtext_lint \
+      rstcheck \
+      rstfmt \
+      snakemake \
+      snakefmt \
+      proselint \
+      sqlfluff \
+      yamllint 
+
+#PIPVENV_DOWNLOAD__END
+
+RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
+ENV PATH=${PATH}:/root/.cargo/bin
+
+RUN mkdir /venvs
+
+ARG TARGETPLATFORM
+COPY --link --from=target-python /usr/local/bin/python3 /usr/local/bin/target-python3
+
+################################
+# Installs python dependencies #
+################################
+COPY --link megalinter /megalinter
+RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
+    mkdir -p "/venvs/megalinter" \
+    && cd "/venvs/megalinter" \
+    && python3 -m crossenv /usr/local/bin/target-python3 . \
+    && source bin/activate \
+    && PYTHONDONTWRITEBYTECODE=1 pip3 install --cache-dir=/var/cache/pip /megalinter
 
 #############################################################################################
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
-#PIP__START
-
-#PIP__END
 
 #PIPVENV__START
 RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
@@ -240,60 +349,95 @@ RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
 
 #PIPVENV__END
 
-############################
-# Install NPM dependencies #
+##################
+# Get base image #
+##################
+ # https://stackoverflow.com/a/73711302/699056
+FROM multiarch/qemu-user-static:x86_64-aarch64 as qemu
+
+FROM python:3.11.3-alpine3.17 AS final
+ARG GITHUB_TOKEN
+
+# https://stackoverflow.com/a/73711302/699056
+COPY --from=qemu /usr/bin/qemu-aarch64-static /usr/bin/
+# https://stackoverflow.com/a/73711302/699056
+# https://stackoverflow.com/a/73359981/699056
+# https://stackoverflow.com/a/71209637/699056
+RUN apk add --update --no-cache libc6-compat \
+                     gcompat \
+                     qemu-x86_64
+
 #############################################################################################
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
+#ARG__START
 
-ENV NODE_OPTIONS="--max-old-space-size=8192" \
-    NODE_ENV=production
-#NPM__START
-WORKDIR /node-deps
-RUN npm --no-cache install --ignore-scripts --omit=dev \
-                jscpd \
-                stylelint \
-                stylelint-config-standard \
-                stylelint-config-sass-guidelines \
-                stylelint-scss \
-                graphql \
-                graphql-schema-linter \
-                npm-groovy-lint \
-                htmlhint \
-                @prantlf/jsonlint \
-                eslint \
-                eslint-plugin-jsonc \
-                @microsoft/eslint-formatter-sarif \
-                v8r \
-                prettier \
-                markdownlint-cli \
-                markdown-link-check \
-                markdown-table-formatter \
-                @stoplight/spectral-cli \
-                secretlint \
-                @secretlint/secretlint-rule-preset-recommend \
-                @secretlint/secretlint-formatter-sarif \
-                cspell \
-                sql-lint \
-                tekton-lint  && \
-    echo "Cleaning npm cache…" \
-    && npm cache clean --force || true \
-    && echo "Changing owner of node_modules files…" \
-    && chown -R "$(id -u)":"$(id -g)" node_modules # fix for https://github.com/npm/cli/issues/5900 \
-    && echo "Removing extra node_module files…" \
-    && rm -rf /root/.npm/_cacache \
-    && find . -name "*.d.ts" -delete \
-    && find . -name "*.map" -delete \
-    && find . -name "*.npmignore" -delete \
-    && find . -name "*.travis.yml" -delete \
-    && find . -name "CHANGELOG.md" -delete \
-    && find . -name "README.md" -delete \
-    && find . -name ".package-lock.json" -delete \
-    && find . -name "package-lock.json" -delete \
-    && find . -name "README.md" -delete
+#ARG__END
+
+####################
+# Run APK installs #
+####################
+
 WORKDIR /
 
-#NPM__END
+#############################################################################################
+## @generated by .automation/build.py using descriptor files, please do not update manually ##
+#############################################################################################
+#APK__START
+RUN apk add --no-cache \
+                bash \
+                ca-certificates \
+                curl \
+                gcc \
+                git \
+                git-lfs \
+                libffi-dev \
+                make \
+                musl-dev \
+                openssh \
+                openjdk11 \
+                py3-pyflakes \
+                nodejs \
+                npm \
+                yarn \
+                helm \
+                gcompat \
+                libc6-compat \
+                libstdc++ \
+                libc-dev \
+                libxml2-dev \
+                libxml2-utils \
+                libgcc \
+                nodejs-current \
+                ruby \
+                ruby-dev \
+                ruby-bundler \
+                ruby-rdoc \
+    && git config --global core.autocrlf true
+#APK__END
+
+# PATH for golang & python
+ENV GOROOT=/usr/lib/go \
+    GOPATH=/go
+    # PYTHONPYCACHEPREFIX="$HOME/.cache/cpython/" NV: not working for all packages :/
+# hadolint ignore=DL3044
+ENV PATH="$PATH":"$GOROOT"/bin:"$GOPATH"/bin
+RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin || true && \
+    # Ignore npm package issues
+    yarn config set ignore-engines true || true
+
+COPY --link --from=python-venv /venvs /venvs
+
+#############################################################################################
+## @generated by .automation/build.py using descriptor files, please do not update manually ##
+#############################################################################################
+#PIP__START
+
+#PIP__END
+
+#PIPVENV_PATH__START
+ENV PATH="${PATH}":/venvs/ansible-lint/cross/bin:/venvs/djlint/cross/bin:/venvs/pylint/cross/bin:/venvs/black/cross/bin:/venvs/flake8/cross/bin:/venvs/isort/cross/bin:/venvs/bandit/cross/bin:/venvs/mypy/cross/bin:/venvs/pyright/cross/bin:/venvs/checkov/cross/bin:/venvs/semgrep/cross/bin:/venvs/rst-lint/cross/bin:/venvs/rstcheck/cross/bin:/venvs/rstfmt/cross/bin:/venvs/snakemake/cross/bin:/venvs/snakefmt/cross/bin:/venvs/proselint/cross/bin:/venvs/sqlfluff/cross/bin:/venvs/yamllint/cross/bin
+#PIPVENV_PATH__END
 
 # Add node packages to path #
 ENV PATH="/node-deps/node_modules/.bin:${PATH}" \
@@ -321,34 +465,8 @@ RUN echo 'gem: --no-document' >> ~/.gemrc && \
 
 #CARGO__END
 
-##############################
-# COPY instructions #
-#############################################################################################
-## @generated by .automation/build.py using descriptor files, please do not update manually ##
-#############################################################################################
-
-#COPY__START
-COPY --link --from=actionlint /usr/local/bin/actionlint /usr/bin/actionlint
-# shellcheck is a dependency for actionlint
-
-COPY --link --from=shellcheck /bin/shellcheck /usr/bin/shellcheck
-COPY --link --from=build-platform /usr/bin/bash-exec /usr/bin/bash-exec
-# Next COPY line commented because already managed by another linter
-# COPY --link --from=shellcheck /bin/shellcheck /usr/bin/shellcheck
-COPY --link --from=shfmt /bin/shfmt /usr/bin/
-COPY --link --from=node_modules /node-deps /node-deps
-COPY --link --from=hadolint /bin/hadolint /usr/bin/hadolint
-COPY --link --from=editorconfig-checker /usr/bin/ec /usr/bin/editorconfig-checker
-COPY --link --from=dotenvlinter /dotenv-linter /usr/bin/dotenv-linter
-COPY --link --from=kubeconform /kubeconform /usr/bin/
-COPY --link --from=checkmake /checkmake /usr/bin/checkmake
-COPY --link --from=protolint /usr/local/bin/protolint /usr/bin/
-COPY --link --from=fetch-ruff /ruff /usr/bin/ruff
-COPY --link --from=gitleaks /usr/bin/gitleaks /usr/bin/
-COPY --link --from=trufflehog /usr/bin/trufflehog /usr/bin/
-COPY --link --from=vale /bin/vale /bin/vale
-COPY --link --from=lychee /usr/local/bin/lychee /usr/bin/
-#COPY__END
+# Don't add link to this one otherwise it doesn't merge correctly
+COPY --from=copy-collector / /
 
 #############################################################################################
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
@@ -379,24 +497,6 @@ RUN curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh |
 # RUN wget --tries=5 -q -O - https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
 #
 #OTHER__END
-
-################################
-# Installs python dependencies #
-################################
-COPY megalinter /megalinter
-RUN PYTHONDONTWRITEBYTECODE=1 python /megalinter/setup.py install \
-    && PYTHONDONTWRITEBYTECODE=1 python /megalinter/setup.py clean --all \
-    && rm -rf /var/cache/apk/* \
-    && find . | grep -E "(/__pycache__$|\.pyc$|\.pyo$)" | xargs rm -rf
-
-#######################################
-# Copy scripts and rules to container #
-#######################################
-COPY megalinter/descriptors /megalinter-descriptors
-COPY TEMPLATES /action/lib/.automation
-
-# Copy server scripts
-COPY server /server
 
 ###########################
 # Get the build arguments #
diff --git a/flavors/security/Dockerfile b/flavors/security/Dockerfile
--- a/flavors/security/Dockerfile
+++ b/flavors/security/Dockerfile
@@ -26,18 +26,200 @@ FROM tenable/terrascan:1.18.1 as terrascan
 FROM alpine/terragrunt:latest as terragrunt
 #FROM__END
 
+FROM --platform=$BUILDPLATFORM python:3.11.3-alpine3.17 AS build-platform
+
+#############################################################################################
+## @generated by .automation/build.py using descriptor files, please do not update manually ##
+#############################################################################################
+#BUILD_PLATFORM_APK__START
+
+#BUILD_PLATFORM_APK__END
+
+#BUILD_PLATFORM_OTHER__START
+# bash-exec installation
+RUN printf '#!/bin/bash \n\nif [[ -x "$1" ]]; then exit 0; else echo "Error: File:[$1] is not executable"; exit 1; fi' > /usr/bin/bash-exec \
+    && chmod +x /usr/bin/bash-exec
+
+#
+#BUILD_PLATFORM_OTHER__END
+
+FROM --platform=$BUILDPLATFORM python:3.11.3-alpine3.17 AS node_modules
+
+#NPM_APK__START
+RUN apk add --update --no-cache \
+                npm
+#NPM_APK__END
+
+############################
+# Install NPM dependencies #
+#############################################################################################
+## @generated by .automation/build.py using descriptor files, please do not update manually ##
+#############################################################################################
+
+ENV NODE_OPTIONS="--max-old-space-size=8192" \
+    NODE_ENV=production
+#NPM__START
+WORKDIR /node-deps
+RUN npm --no-cache install --ignore-scripts --omit=dev \
+                secretlint \
+                @secretlint/secretlint-rule-preset-recommend \
+                @secretlint/secretlint-formatter-sarif  && \
+    echo "Cleaning npm cache…" \
+    && npm cache clean --force || true \
+    && echo "Changing owner of node_modules files…" \
+    && chown -R "$(id -u)":"$(id -g)" node_modules # fix for https://github.com/npm/cli/issues/5900 \
+    && echo "Removing extra node_module files…" \
+    && rm -rf /root/.npm/_cacache \
+    && find . -name "*.d.ts" -delete \
+    && find . -name "*.map" -delete \
+    && find . -name "*.npmignore" -delete \
+    && find . -name "*.travis.yml" -delete \
+    && find . -name "CHANGELOG.md" -delete \
+    && find . -name "README.md" -delete \
+    && find . -name ".package-lock.json" -delete \
+    && find . -name "package-lock.json" -delete \
+    && find . -name "README.md" -delete
+WORKDIR /
+
+#NPM__END
+
+FROM busybox AS copy-collector
+
+##############################
+# COPY instructions #
+#############################################################################################
+## @generated by .automation/build.py using descriptor files, please do not update manually ##
+#############################################################################################
+
+#COPY__START
+COPY --link --from=build-platform /usr/bin/bash-exec /usr/bin/bash-exec
+COPY --link --from=shellcheck /bin/shellcheck /usr/bin/shellcheck
+COPY --link --from=hadolint /bin/hadolint /usr/bin/hadolint
+COPY --link --from=kubeconform /kubeconform /usr/bin/
+COPY --link --from=dustilock /usr/bin/dustilock /usr/bin/dustilock
+COPY --link --from=gitleaks /usr/bin/gitleaks /usr/bin/
+COPY --link --from=kics /app/bin/kics /usr/bin/
+COPY --from=kics /app/bin/assets /opt/kics/assets/
+COPY --link --from=node_modules /node-deps /node-deps
+COPY --link --from=trufflehog /usr/bin/trufflehog /usr/bin/
+COPY --link --from=tflint /usr/local/bin/tflint /usr/bin/
+COPY --link --from=terrascan /go/bin/terrascan /usr/bin/
+COPY --link --from=terragrunt /usr/local/bin/terragrunt /usr/bin/
+#COPY__END
+
+#######################################
+# Copy scripts and rules to container #
+#######################################
+COPY --link megalinter/descriptors /megalinter-descriptors
+COPY --link TEMPLATES /action/lib/.automation
+
+FROM --platform=$TARGETPLATFORM python:3.11.3-alpine3.17 AS target-python
+FROM --platform=$BUILDPLATFORM python:3.11.3-alpine3.17 AS python-venv
+
+
+#############################################################################################
+## @generated by .automation/build.py using descriptor files, please do not update manually ##
+#############################################################################################
+
+#PIPVENV_BUILDDEPS__START
+RUN apk add --update --no-cache \
+                gcc \
+                libffi-dev \
+                musl-dev \
+                make \
+                curl \
+                openssl-dev \
+                g++ \
+                cmake
+#PIPVENV_BUILDDEPS__END
+
+#PIPVENV_DOWNLOAD__START
+RUN --mount=type=cache,id=pip,sharing=locked,target=/var/cache/pip,uid=0 \
+    mkdir /download \
+    && PYTHONDONTWRITEBYTECODE=1 pip3 --disable-pip-version-check install --cache-dir=/var/cache/pip --upgrade pip crossenv \
+&& pip download --cache-dir=/var/cache/pip --dest "/download" \
+      ansible-lint \
+      cfn-lint \
+      bandit \
+      bandit_sarif_formatter \
+      bandit[toml] \
+      packaging \
+      checkov \
+      semgrep 
+
+#PIPVENV_DOWNLOAD__END
+
+RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
+ENV PATH=${PATH}:/root/.cargo/bin
+
+RUN mkdir /venvs
+
+ARG TARGETPLATFORM
+COPY --link --from=target-python /usr/local/bin/python3 /usr/local/bin/target-python3
+
+################################
+# Installs python dependencies #
+################################
+COPY --link megalinter /megalinter
+RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
+    mkdir -p "/venvs/megalinter" \
+    && cd "/venvs/megalinter" \
+    && python3 -m crossenv /usr/local/bin/target-python3 . \
+    && source bin/activate \
+    && PYTHONDONTWRITEBYTECODE=1 pip3 install --cache-dir=/var/cache/pip /megalinter
+
+#############################################################################################
+## @generated by .automation/build.py using descriptor files, please do not update manually ##
+#############################################################################################
+
+#PIPVENV__START
+RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
+   mkdir -p "/venvs/ansible-lint" \
+ && cd "/venvs/ansible-lint" \
+ && python3 -m crossenv /usr/local/bin/target-python3 . \
+ && source bin/activate \
+ && PYTHONDONTWRITEBYTECODE=1  pip3 --disable-pip-version-check install --find-links=/download --cache-dir=/var/cache/pip ansible-lint
+RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
+   mkdir -p "/venvs/cfn-lint" \
+ && cd "/venvs/cfn-lint" \
+ && python3 -m crossenv /usr/local/bin/target-python3 . \
+ && source bin/activate \
+ && PYTHONDONTWRITEBYTECODE=1  pip3 --disable-pip-version-check install --find-links=/download --cache-dir=/var/cache/pip cfn-lint
+RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
+   mkdir -p "/venvs/bandit" \
+ && cd "/venvs/bandit" \
+ && python3 -m crossenv /usr/local/bin/target-python3 . \
+ && source bin/activate \
+ && PYTHONDONTWRITEBYTECODE=1  pip3 --disable-pip-version-check install --find-links=/download --cache-dir=/var/cache/pip bandit bandit_sarif_formatter bandit[toml]
+RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
+   mkdir -p "/venvs/checkov" \
+ && cd "/venvs/checkov" \
+ && python3 -m crossenv /usr/local/bin/target-python3 . \
+ && source bin/activate \
+ && PYTHONDONTWRITEBYTECODE=1  pip3 --disable-pip-version-check install --find-links=/download --cache-dir=/var/cache/pip packaging checkov
+RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
+   mkdir -p "/venvs/semgrep" \
+ && cd "/venvs/semgrep" \
+ && python3 -m crossenv /usr/local/bin/target-python3 . \
+ && source bin/activate \
+ && PYTHONDONTWRITEBYTECODE=1  pip3 --disable-pip-version-check install --find-links=/download --cache-dir=/var/cache/pip semgrep
+
+#PIPVENV__END
+
 ##################
 # Get base image #
 ##################
-# https://stackoverflow.com/a/73711302/699056
+ # https://stackoverflow.com/a/73711302/699056
 FROM multiarch/qemu-user-static:x86_64-aarch64 as qemu
 
-FROM python:3.11.4-alpine3.17
+FROM python:3.11.3-alpine3.17 AS final
 ARG GITHUB_TOKEN
 
 # https://stackoverflow.com/a/73711302/699056
 COPY --from=qemu /usr/bin/qemu-aarch64-static /usr/bin/
 # https://stackoverflow.com/a/73711302/699056
+# https://stackoverflow.com/a/73359981/699056
+# https://stackoverflow.com/a/71209637/699056
 RUN apk add --update --no-cache libc6-compat \
                      gcompat \
                      qemu-x86_64
@@ -97,6 +279,8 @@ RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin || true && \
     # Ignore npm package issues
     yarn config set ignore-engines true || true
 
+COPY --link --from=python-venv /venvs /venvs
+
 #############################################################################################
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
@@ -104,72 +288,9 @@ RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin || true && \
 
 #PIP__END
 
-#PIPVENV__START
-RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
-   mkdir -p "/venvs/ansible-lint" \
- && cd "/venvs/ansible-lint" \
- && python3 -m crossenv /usr/local/bin/target-python3 . \
- && source bin/activate \
- && PYTHONDONTWRITEBYTECODE=1  pip3 --disable-pip-version-check install --find-links=/download --cache-dir=/var/cache/pip ansible-lint
-RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
-   mkdir -p "/venvs/cfn-lint" \
- && cd "/venvs/cfn-lint" \
- && python3 -m crossenv /usr/local/bin/target-python3 . \
- && source bin/activate \
- && PYTHONDONTWRITEBYTECODE=1  pip3 --disable-pip-version-check install --find-links=/download --cache-dir=/var/cache/pip cfn-lint
-RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
-   mkdir -p "/venvs/bandit" \
- && cd "/venvs/bandit" \
- && python3 -m crossenv /usr/local/bin/target-python3 . \
- && source bin/activate \
- && PYTHONDONTWRITEBYTECODE=1  pip3 --disable-pip-version-check install --find-links=/download --cache-dir=/var/cache/pip bandit bandit_sarif_formatter bandit[toml]
-RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
-   mkdir -p "/venvs/checkov" \
- && cd "/venvs/checkov" \
- && python3 -m crossenv /usr/local/bin/target-python3 . \
- && source bin/activate \
- && PYTHONDONTWRITEBYTECODE=1  pip3 --disable-pip-version-check install --find-links=/download --cache-dir=/var/cache/pip packaging checkov
-RUN --mount=type=cache,id=pip,sharing=shared,target=/var/cache/pip,uid=0 \
-   mkdir -p "/venvs/semgrep" \
- && cd "/venvs/semgrep" \
- && python3 -m crossenv /usr/local/bin/target-python3 . \
- && source bin/activate \
- && PYTHONDONTWRITEBYTECODE=1  pip3 --disable-pip-version-check install --find-links=/download --cache-dir=/var/cache/pip semgrep
-
-#PIPVENV__END
-
-############################
-# Install NPM dependencies #
-#############################################################################################
-## @generated by .automation/build.py using descriptor files, please do not update manually ##
-#############################################################################################
-
-ENV NODE_OPTIONS="--max-old-space-size=8192" \
-    NODE_ENV=production
-#NPM__START
-WORKDIR /node-deps
-RUN npm --no-cache install --ignore-scripts --omit=dev \
-                secretlint \
-                @secretlint/secretlint-rule-preset-recommend \
-                @secretlint/secretlint-formatter-sarif  && \
-    echo "Cleaning npm cache…" \
-    && npm cache clean --force || true \
-    && echo "Changing owner of node_modules files…" \
-    && chown -R "$(id -u)":"$(id -g)" node_modules # fix for https://github.com/npm/cli/issues/5900 \
-    && echo "Removing extra node_module files…" \
-    && rm -rf /root/.npm/_cacache \
-    && find . -name "*.d.ts" -delete \
-    && find . -name "*.map" -delete \
-    && find . -name "*.npmignore" -delete \
-    && find . -name "*.travis.yml" -delete \
-    && find . -name "CHANGELOG.md" -delete \
-    && find . -name "README.md" -delete \
-    && find . -name ".package-lock.json" -delete \
-    && find . -name "package-lock.json" -delete \
-    && find . -name "README.md" -delete
-WORKDIR /
-
-#NPM__END
+#PIPVENV_PATH__START
+ENV PATH="${PATH}":/venvs/ansible-lint/cross/bin:/venvs/cfn-lint/cross/bin:/venvs/bandit/cross/bin:/venvs/checkov/cross/bin:/venvs/semgrep/cross/bin
+#PIPVENV_PATH__END
 
 # Add node packages to path #
 ENV PATH="/node-deps/node_modules/.bin:${PATH}" \
@@ -195,27 +316,8 @@ ENV PATH="/node-deps/node_modules/.bin:${PATH}" \
 
 #CARGO__END
 
-##############################
-# COPY instructions #
-#############################################################################################
-## @generated by .automation/build.py using descriptor files, please do not update manually ##
-#############################################################################################
-
-#COPY__START
-COPY --link --from=build-platform /usr/bin/bash-exec /usr/bin/bash-exec
-COPY --link --from=shellcheck /bin/shellcheck /usr/bin/shellcheck
-COPY --link --from=hadolint /bin/hadolint /usr/bin/hadolint
-COPY --link --from=kubeconform /kubeconform /usr/bin/
-COPY --link --from=dustilock /usr/bin/dustilock /usr/bin/dustilock
-COPY --link --from=gitleaks /usr/bin/gitleaks /usr/bin/
-COPY --link --from=kics /app/bin/kics /usr/bin/
-COPY --from=kics /app/bin/assets /opt/kics/assets/
-COPY --link --from=node_modules /node-deps /node-deps
-COPY --link --from=trufflehog /usr/bin/trufflehog /usr/bin/
-COPY --link --from=tflint /usr/local/bin/tflint /usr/bin/
-COPY --link --from=terrascan /go/bin/terrascan /usr/bin/
-COPY --link --from=terragrunt /usr/local/bin/terragrunt /usr/bin/
-#COPY__END
+# Don't add link to this one otherwise it doesn't merge correctly
+COPY --from=copy-collector / /
 
 #############################################################################################
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
@@ -252,24 +354,6 @@ RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | 
 # RUN wget --tries=5 -q -O - https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
 #
 #OTHER__END
-
-################################
-# Installs python dependencies #
-################################
-COPY megalinter /megalinter
-RUN PYTHONDONTWRITEBYTECODE=1 python /megalinter/setup.py install \
-    && PYTHONDONTWRITEBYTECODE=1 python /megalinter/setup.py clean --all \
-    && rm -rf /var/cache/apk/* \
-    && find . | grep -E "(/__pycache__$|\.pyc$|\.pyo$)" | xargs rm -rf
-
-#######################################
-# Copy scripts and rules to container #
-#######################################
-COPY megalinter/descriptors /megalinter-descriptors
-COPY TEMPLATES /action/lib/.automation
-
-# Copy server scripts
-COPY server /server
 
 ###########################
 # Get the build arguments #
