Install actionlint from docker image's binary to remove apk go

diff --git a/flavors/go/Dockerfile b/flavors/go/Dockerfile
--- a/flavors/go/Dockerfile
+++ b/flavors/go/Dockerfile
@@ -11,6 +11,11 @@
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
 #FROM__START
+FROM rhysd/actionlint:1.6.23 as actionlint
+# shellcheck is a dependency for actionlint
+FROM koalaman/shellcheck:v0.9.0 as shellcheck
+
+FROM koalaman/shellcheck:v0.9.0 as shellcheck
 FROM mvdan/shfmt:latest-alpine as shfmt
 FROM hadolint/hadolint:v2.12.0-alpine as hadolint
 FROM mstruebing/editorconfig-checker:2.7.0 as editorconfig-checker
@@ -53,8 +58,9 @@ RUN apk add --update --no-cache \
                 make \
                 musl-dev \
                 openssh \
-                go \
                 openjdk11 \
+                py3-pyflakes \
+                go \
                 nodejs \
                 npm \
                 yarn \
@@ -192,6 +198,11 @@ ENV PATH="/root/.cargo/bin:${PATH}"
 #############################################################################################
 
 #COPY__START
+COPY --from=actionlint /usr/local/bin/actionlint /usr/bin/actionlint
+# shellcheck is a dependency for actionlint
+COPY --from=shellcheck /bin/shellcheck /usr/bin/shellcheck
+
+COPY --from=shellcheck /bin/shellcheck /usr/bin/shellcheck
 COPY --from=shfmt /bin/shfmt /usr/bin/
 COPY --from=hadolint /bin/hadolint /usr/bin/hadolint
 COPY --from=editorconfig-checker /usr/bin/ec /usr/bin/editorconfig-checker
@@ -205,19 +216,17 @@ COPY --from=gitleaks /usr/bin/gitleaks /usr/bin/
 #############################################################################################
 #OTHER__START
 # actionlint installation
-ENV GO111MODULE=on
-RUN go install github.com/rhysd/actionlint/cmd/actionlint@latest && go clean --cache \
+# Managed with COPY --from=actionlint /usr/local/bin/actionlint /usr/bin/actionlint
+# shellcheck is a dependency for actionlint
+COPY --from=shellcheck /bin/shellcheck /usr/bin/shellcheck
+
 
 # bash-exec installation
-    && printf '#!/bin/bash \n\nif [[ -x "$1" ]]; then exit 0; else echo "Error: File:[$1] is not executable"; exit 1; fi' > /usr/bin/bash-exec \
+RUN printf '#!/bin/bash \n\nif [[ -x "$1" ]]; then exit 0; else echo "Error: File:[$1] is not executable"; exit 1; fi' > /usr/bin/bash-exec \
     && chmod +x /usr/bin/bash-exec \
 
 # shellcheck installation
-    && ML_THIRD_PARTY_DIR="/third-party/shellcheck" \
-    && mkdir -p ${ML_THIRD_PARTY_DIR} \
-    && wget -qO- "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" | tar -xJv --directory ${ML_THIRD_PARTY_DIR} \
-    && mv "${ML_THIRD_PARTY_DIR}/shellcheck-stable/shellcheck" /usr/bin/ \
-    && find ${ML_THIRD_PARTY_DIR} -type f -not -name 'LICENSE*' -delete -o -type d -empty -delete \
+# Managed with COPY --from=shellcheck /bin/shellcheck /usr/bin/shellcheck
 
 # shfmt installation
 # Managed with COPY --from=shfmt /bin/shfmt /usr/bin/
