Add shell script linters to ci_light flavor (#1299)
* Add shell script linters to ci_light flavor

Use-case: many of my Docker-related projects have glue shell scripts (e.g., `/entrypoint.sh`) that are added to images (e.g., `COPY entrypoint.sh /`) that are run when the image is run (e.g., `ENTRYPOINT ["/entrypoint.sh"]`) and I would like to have them scanned without having to pull down the full scanner.

* Add sh linters to ci_light flavor + build

Co-authored-by: nvuillam <nicolas.vuillamy@gmail.com>

diff --git a/flavors/ci_light/Dockerfile b/flavors/ci_light/Dockerfile
--- a/flavors/ci_light/Dockerfile
+++ b/flavors/ci_light/Dockerfile
@@ -11,6 +11,7 @@
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
 #FROM__START
+FROM mvdan/shfmt:latest-alpine as shfmt
 FROM hadolint/hadolint:v2.7.0-alpine as hadolint
 #FROM__END
 
@@ -126,6 +127,23 @@ ENV PATH="/node_modules/.bin:${PATH}"
 #OTHER__START
 # GIT installation
 RUN git config --global core.autocrlf true
+
+# bash-exec installation
+RUN printf '#!/bin/bash \n\nif [[ -x "$1" ]]; then exit 0; else echo "Error: File:[$1] is not executable"; exit 1; fi' > /usr/bin/bash-exec \
+    && chmod +x /usr/bin/bash-exec
+
+
+# shellcheck installation
+RUN ML_THIRD_PARTY_DIR="/third-party/shellcheck" \
+    && mkdir -p ${ML_THIRD_PARTY_DIR} \
+    && wget -qO- "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" | tar -xJv --directory ${ML_THIRD_PARTY_DIR} \
+    && mv "${ML_THIRD_PARTY_DIR}/shellcheck-stable/shellcheck" /usr/bin/ \
+    && find ${ML_THIRD_PARTY_DIR} -type f -not -name 'LICENSE*' -delete -o -type d -empty -delete \
+    && shellcheck --version
+
+
+# shfmt installation
+COPY --from=shfmt /bin/shfmt /usr/bin/
 
 # hadolint installation
 COPY --from=hadolint /bin/hadolint /usr/bin/hadolint
