Cleaning of CVE exceptions + manual upgrades (Java 21, PMD7, Powershell) (#3518)
* Draft: cleaning

* Remove useless package-lock.json

* trivy exceptions

* Upgrade PMD to 7.1.0

* Undowngrade kubescape

* Upgrade powershell

* trivy ignore

* trivy exceptions

* Upgrade java to openjdk21

* Upgrade terrascan

* trivyignore

* Downgrade terrascan

* upgrade exceptions

* Fix PMD7 install

* powershell exceptions

* Fix pmd7 install

* Test setup disable sarif by default

* sfdx-scanner exceptions

* Fix pmd install

* Fix pmd installation & class

* Update groovy test files

* [MegaLinter] Apply linters fixes

* Force java17 for npm-groovy-lint

* tsql-lint exceptions

* Downgrade kubescape

* Downgrade kubescape

* Changelog

* Exceptions for kubescape

---------

Co-authored-by: nvuillam <nvuillam@users.noreply.github.com>

diff --git a/flavors/java/Dockerfile b/flavors/java/Dockerfile
--- a/flavors/java/Dockerfile
+++ b/flavors/java/Dockerfile
@@ -40,7 +40,7 @@ ARG GITHUB_TOKEN
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
 #ARG__START
-ARG PMD_VERSION=6.55.0
+ARG PMD_VERSION=7.1.0
 #ARG__END
 
 ####################
@@ -64,11 +64,12 @@ RUN apk add --no-cache \
                 make \
                 musl-dev \
                 openssh \
-                openjdk17 \
+                openjdk21 \
                 py3-pyflakes \
                 nodejs \
                 npm \
                 yarn \
+                openjdk17 \
                 helm \
                 gcompat \
                 libc6-compat \
@@ -270,12 +271,12 @@ RUN ALPINE_GLIBC_BASE_URL="https://github.com/sgerrand/alpine-pkg-glibc/releases
 
 
 # JAVA installation
-ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
+ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk
 ENV PATH="$JAVA_HOME/bin:${PATH}"
 
 # KOTLIN installation
 # Next line commented because already managed by another linter
-# ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
+# ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk
 # Next line commented because already managed by another linter
 # ENV PATH="$JAVA_HOME/bin:${PATH}"
 
@@ -310,10 +311,7 @@ RUN printf '#!/bin/bash \n\nif [[ -x "$1" ]]; then exit 0; else echo "Error: Fil
     && wget -q -O - https://raw.githubusercontent.com/dotenv-linter/dotenv-linter/master/install.sh | sh -s
 
 # npm-groovy-lint installation
-# Next line commented because already managed by another linter
-# ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
-# Next line commented because already managed by another linter
-# ENV PATH="$JAVA_HOME/bin:${PATH}"
+ENV JAVA_HOME_17=/usr/lib/jvm/java-17-openjdk
 
 # checkstyle installation
 RUN --mount=type=secret,id=GITHUB_TOKEN CHECKSTYLE_LATEST=$(curl -s \
@@ -328,11 +326,11 @@ RUN --mount=type=secret,id=GITHUB_TOKEN CHECKSTYLE_LATEST=$(curl -s \
 
 
 # pmd installation
-RUN wget --quiet https://github.com/pmd/pmd/releases/download/pmd_releases%2F${PMD_VERSION}/pmd-bin-${PMD_VERSION}.zip && \
-    unzip pmd-bin-${PMD_VERSION}.zip && \
-    rm pmd-bin-${PMD_VERSION}.zip && \
-    mv pmd-bin-${PMD_VERSION} /usr/bin/pmd && \
-    chmod +x /usr/bin/pmd/bin/run.sh \
+RUN wget --quiet https://github.com/pmd/pmd/releases/download/pmd_releases%2F${PMD_VERSION}/pmd-dist-${PMD_VERSION}-bin.zip && \
+    unzip pmd-dist-${PMD_VERSION}-bin.zip || echo "Error unzipping" && \
+    rm pmd-dist-${PMD_VERSION}-bin.zip || echo "Error rm" && \
+    mv pmd-bin-${PMD_VERSION} /usr/bin/pmd || echo "Error mv" && \
+    chmod +x /usr/bin/pmd/bin/pmd || echo "Error chmod" \
 
 # ktlint installation
     && curl --retry 5 --retry-delay 5 -sSLO https://github.com/pinterest/ktlint/releases/latest/download/ktlint && \
diff --git a/linters/java_pmd/Dockerfile b/linters/java_pmd/Dockerfile
--- a/linters/java_pmd/Dockerfile
+++ b/linters/java_pmd/Dockerfile
@@ -24,7 +24,7 @@ ARG GITHUB_TOKEN
 ## @generated by .automation/build.py using descriptor files, please do not update manually ##
 #############################################################################################
 #ARG__START
-ARG PMD_VERSION=6.55.0
+ARG PMD_VERSION=7.1.0
 #ARG__END
 
 ####################
@@ -48,7 +48,7 @@ RUN apk add --no-cache \
                 make \
                 musl-dev \
                 openssh \
-                openjdk17 \
+                openjdk21 \
     && git config --global core.autocrlf true
 #APK__END
 
@@ -123,15 +123,15 @@ ENV PATH="/node-deps/node_modules/.bin:${PATH}" \
 #############################################################################################
 #OTHER__START
 # JAVA installation
-ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
+ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk
 ENV PATH="$JAVA_HOME/bin:${PATH}"
 
 # pmd installation
-RUN wget --quiet https://github.com/pmd/pmd/releases/download/pmd_releases%2F${PMD_VERSION}/pmd-bin-${PMD_VERSION}.zip && \
-    unzip pmd-bin-${PMD_VERSION}.zip && \
-    rm pmd-bin-${PMD_VERSION}.zip && \
-    mv pmd-bin-${PMD_VERSION} /usr/bin/pmd && \
-    chmod +x /usr/bin/pmd/bin/run.sh
+RUN wget --quiet https://github.com/pmd/pmd/releases/download/pmd_releases%2F${PMD_VERSION}/pmd-dist-${PMD_VERSION}-bin.zip && \
+    unzip pmd-dist-${PMD_VERSION}-bin.zip || echo "Error unzipping" && \
+    rm pmd-dist-${PMD_VERSION}-bin.zip || echo "Error rm" && \
+    mv pmd-bin-${PMD_VERSION} /usr/bin/pmd || echo "Error mv" && \
+    chmod +x /usr/bin/pmd/bin/pmd || echo "Error chmod"
 
 
 #OTHER__END
