Starting refactor to make multiarch testing easier

diff --git a/.github/workflows/deploy-DEV.yml b/.github/workflows/deploy-DEV.yml
--- a/.github/workflows/deploy-DEV.yml
+++ b/.github/workflows/deploy-DEV.yml
@@ -46,226 +46,108 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-
   build:
-    # Name the Job
     name: Tests + Deploy Docker Image - DEV
-    # Set the agent to run on
-    runs-on: ubuntu-latest
-    permissions: read-all
     # Prevent duplicate run from happening when a forked push is committed
     if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, 'skip deploy')
-    # Set max build time for the job
-    timeout-minutes: 120
-    ##################
-    # Load all steps #
-    ##################
-    steps:
-      ##########################
-      # Checkout the code base #
-      ##########################
-      - name: Checkout Code
-        uses: actions/checkout@v3
-
-      #######################
-      # Docker Buildx setup #
-      #######################
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-
-      ########################
-      # Get the current date #
-      ########################
-      - name: Get current date
-        run: echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >>"$GITHUB_ENV"
-
-      ########################
-      # Build image tag name #
-      ########################
-      - name: Build image tag name
-        id: image_tag
-        run: |
-          BRANCH_NAME="${GITHUB_REF##*/}"
-          TAG="test-${{ github.actor }}-${BRANCH_NAME}"
-          echo "Tag name: ${TAG}"
-          echo "tag=${TAG}" >>"$GITHUB_OUTPUT"
-
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-
-      # Free disk space
-      - name: Free Disk space
-        shell: bash
-        run: |
-          sudo rm -rf /usr/local/lib/android  # will release about 10 GB if you don't need Android
-          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
-
-      ###################################
-      # Build image locally for testing #
-      ###################################
-      - name: Build MegaLinter Docker Image (quick)
-        if: "contains(github.event.head_commit.message, 'quick build')"
-        id: docker_build_quick
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          file: Dockerfile-quick
-          platforms: linux/amd64,linux/arm64
-          build-args: |
-            BUILD_DATE=${{ env.BUILD_DATE }}
-            BUILD_REVISION=${{ github.sha }}
-            BUILD_VERSION=${{ steps.image_tag.outputs.tag }}
-            MEGA_LINTER_BASE_IMAGE="oxsecurity/megalinter:beta"
-          load: true
-          push: false
-          secrets: |
-            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
-          tags: |
-            oxsecurity/megalinter:${{ steps.image_tag.outputs.tag }}
-        timeout-minutes: 90
-
-      #######################################
-      # Build image (full for forked repos) #
-      #######################################
-      - name: Build MegaLinter Docker Image (full from forks)
-        if: |
+    uses: -build-docker.yml
+    with:
+      tagTemplate: "test-${{ github.actor }}-${BRANCH_NAME}"
+      shouldLoginDockerHub: |
+        (
+          (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) ||
+          (github.event_name == 'push' && github.repository == 'oxsecurity/megalinter')
+        )
+      shouldLoginGithub: false
+      dockerfile: ${{ (contains(github.event.head_commit.message, 'quick build') && 'Dockerfile-quick') || 'Dockerfile' }}
+      push: false
+      load: ${{ !(
           (
           (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) ||
           (github.event_name == 'push' && github.repository != 'oxsecurity/megalinter')
           )
           &&
           !contains(github.event.head_commit.message, 'quick build')
-        id: docker_build
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          file: Dockerfile
-          platforms: linux/amd64,linux/arm64
-          build-args: |
-            BUILD_DATE=${{ env.BUILD_DATE }}
-            BUILD_REVISION=${{ github.sha }}
-            BUILD_VERSION=${{ steps.image_tag.outputs.tag }}
-          load: false
-          push: false
-          secrets: |
-            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
-          tags: |
-            oxsecurity/megalinter:${{ steps.image_tag.outputs.tag }}
-          outputs: type=oci,dest=/tmp/image.tar
-        timeout-minutes: 360 #90 - Temp increasing this to see how long it takes
-      - name: Load OCI
-        shell: bash
-        run: |
-          cat /tmp/image.tar | docker load
-          rm -f /tmp/image.tar
+        )
+      }}
+      imageName: megalinter
 
-      ####################################
-      # Build image (full for main repo) #
-      ####################################
-      - name: Build MegaLinter Docker Image (full from main repo) & push
-        if: |
-          (
-          (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) ||
-          (github.event_name == 'push' && github.repository == 'oxsecurity/megalinter')
-          )
-          &&
-          !contains(github.event.head_commit.message, 'quick build')
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          file: Dockerfile
-          platforms: linux/amd64,linux/arm64
-          build-args: |
-            BUILD_DATE=${{ env.BUILD_DATE }}
-            BUILD_REVISION=${{ github.sha }}
-            BUILD_VERSION=${{ steps.image_tag.outputs.tag }}
-          load: true
-          push: false
-          secrets: |
-            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
-          tags: |
-            oxsecurity/megalinter:${{ steps.image_tag.outputs.tag }}
-
-      #####################################
-      # Run Linter test cases #
-      #####################################
-      - name: Run Test Cases
-        shell: bash
-        run: |
-          GITHUB_REPOSITORY=$([ "${{ github.event_name }}" == "pull_request" ] && echo "${{ github.event.pull_request.head.repo.full_name }}" || echo "${{ github.repository }}")
-          GITHUB_BRANCH=$([ "${{ github.event_name }}" == "pull_request" ] && echo "${{ github.head_ref }}" || echo "${{ github.ref_name }}")
-
-          export CI_ENV="$(bash <(curl -s https://codecov.io/env)) -e GITHUB_ACTIONS"
-          TEST_KEYWORDS_TO_USE=""
-          if [[ "${{ github.event.head_commit.message }}" == *"TEST_KEYWORDS="* ]]; then
-            COMMIT_MSG="${{ github.event.head_commit.message }}"
-            TEST_KEYWORDS_TO_USE=${COMMIT_MSG#*TEST_KEYWORDS=}
-            echo "Run only tests with keywords ${TEST_KEYWORDS_TO_USE}"
-            if [[ "${TEST_KEYWORDS_TO_USE}" =~ $'\r' ]]; then
-                echo "Problem while parsing test keywords: switch back to all tests"
-                TEST_KEYWORDS_TO_USE=""
-            fi
-          fi
-          docker image ls
-          docker run $CI_ENV -e TEST_CASE_RUN=true -e OUTPUT_FORMAT=text -e OUTPUT_FOLDER=${{ github.sha }} -e OUTPUT_DETAIL=detailed -e GITHUB_SHA=${{ github.sha }} -e GITHUB_REPOSITORY=${GITHUB_REPOSITORY} -e GITHUB_BRANCH=${GITHUB_BRANCH} -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" -e TEST_KEYWORDS="${TEST_KEYWORDS_TO_USE}" -e MEGALINTER_VOLUME_ROOT="${GITHUB_WORKSPACE}" -v "/var/run/docker.sock:/var/run/docker.sock:rw" -v ${GITHUB_WORKSPACE}:/tmp/lint oxsecurity/megalinter:${{ steps.image_tag.outputs.tag }}
-        timeout-minutes: 90
-
-      #####################################
-      # Run Linter against ALL code base  #
-      #####################################
-      - name: Run against all code base
-        if: "!contains(github.event.head_commit.message, 'quick build')"
-        shell: bash
-        run: docker run -e GITHUB_REPOSITORY="${{ github.repository }}" -e GITHUB_SHA="${{ github.sha }}" -e GITHUB_TOKEN="${{ github.token }}" -e GITHUB_RUN_ID="${{ github.run_id }}" -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" -v "/var/run/docker.sock:/var/run/docker.sock:rw" -v ${GITHUB_WORKSPACE}:/tmp/lint oxsecurity/megalinter:${{ steps.image_tag.outputs.tag }}
-        timeout-minutes: 15
-
-      # Upload MegaLinter artifacts
-      - name: Archive production artifacts
-        if: ${{ success() }} || ${{ failure() }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: MegaLinter reports
-          path: |
-            megalinter-reports
-            mega-linter.log
-            linter-helps.json
-            linter-versions.json
-
-      - name: debug
-        if: ${{ success() }} || ${{ failure() }}
-        run: echo ${{ steps.docker_build.outcome }}
-
-      # Test mega-linter-runner with newly created image
-      - name: Setup Node
-        if: ${{ steps.docker_build.outcome }} == 'success' && !contains(github.event.head_commit.message, 'quick build')
-        uses: actions/setup-node@v3.7.0
-        with:
-          node-version: "12"
-      - name: Install NPM dependencies
-        if: ${{ steps.docker_build.outcome }} == 'success' && !contains(github.event.head_commit.message, 'quick build')
-        run: cd mega-linter-runner && sudo yarn install --frozen-lockfile && sudo npm link
-      - name: Run mega-linter-runner tests
-        if: ${{ steps.docker_build.outcome }} == 'success' && !contains(github.event.head_commit.message, 'quick build')
-        run: cd mega-linter-runner && MEGALINTER_RELEASE=${{ steps.image_tag.outputs.tag }} MEGALINTER_NO_DOCKER_PULL=true npm run test
-
-      ##############################################
-      # Check Docker image security with Trivy #
-      ##############################################
-
-      - name: Run Trivy vulnerability scanner
-        uses: aquasecurity/trivy-action@master
-        with:
-          image-ref: "docker.io/oxsecurity/megalinter:${{ steps.image_tag.outputs.tag }}"
-          format: 'table'
-          exit-code: '1'
-          ignore-unfixed: true
-          scanners: vuln
-          vuln-type: 'os,library'
-          severity: 'CRITICAL,HIGH'
-          timeout: 15m0s
+#    steps:
+#
+#      #####################################
+#      # Run Linter test cases #
+#      #####################################
+#      - name: Run Test Cases
+#        shell: bash
+#        run: |
+#          GITHUB_REPOSITORY=$([ "${{ github.event_name }}" == "pull_request" ] && echo "${{ github.event.pull_request.head.repo.full_name }}" || echo "${{ github.repository }}")
+#          GITHUB_BRANCH=$([ "${{ github.event_name }}" == "pull_request" ] && echo "${{ github.head_ref }}" || echo "${{ github.ref_name }}")
+#
+#          export CI_ENV="$(bash <(curl -s https://codecov.io/env)) -e GITHUB_ACTIONS"
+#          TEST_KEYWORDS_TO_USE=""
+#          if [[ "${{ github.event.head_commit.message }}" == *"TEST_KEYWORDS="* ]]; then
+#            COMMIT_MSG="${{ github.event.head_commit.message }}"
+#            TEST_KEYWORDS_TO_USE=${COMMIT_MSG#*TEST_KEYWORDS=}
+#            echo "Run only tests with keywords ${TEST_KEYWORDS_TO_USE}"
+#            if [[ "${TEST_KEYWORDS_TO_USE}" =~ $'\r' ]]; then
+#                echo "Problem while parsing test keywords: switch back to all tests"
+#                TEST_KEYWORDS_TO_USE=""
+#            fi
+#          fi
+#          docker image ls
+#          docker run $CI_ENV -e TEST_CASE_RUN=true -e OUTPUT_FORMAT=text -e OUTPUT_FOLDER=${{ github.sha }} -e OUTPUT_DETAIL=detailed -e GITHUB_SHA=${{ github.sha }} -e GITHUB_REPOSITORY=${GITHUB_REPOSITORY} -e GITHUB_BRANCH=${GITHUB_BRANCH} -e PAT="${{ secrets.PAT }}" -e TEST_KEYWORDS="${TEST_KEYWORDS_TO_USE}" -e MEGALINTER_VOLUME_ROOT="${GITHUB_WORKSPACE}" -v "/var/run/docker.sock:/var/run/docker.sock:rw" -v ${GITHUB_WORKSPACE}:/tmp/lint oxsecurity/megalinter:${{ steps.image_tag.outputs.tag }}
+#        timeout-minutes: 90
+#
+#      #####################################
+#      # Run Linter against ALL code base  #
+#      #####################################
+#      - name: Run against all code base
+#        if: "!contains(github.event.head_commit.message, 'quick build')"
+#        shell: bash
+#        run: docker run -e GITHUB_REPOSITORY="${{ github.repository }}" -e GITHUB_SHA="${{ github.sha }}" -e GITHUB_TOKEN="${{ github.token }}" -e GITHUB_RUN_ID="${{ github.run_id }}" -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" -v "/var/run/docker.sock:/var/run/docker.sock:rw" -v ${GITHUB_WORKSPACE}:/tmp/lint oxsecurity/megalinter:${{ steps.image_tag.outputs.tag }}
+#        timeout-minutes: 15
+#
+#      # Upload MegaLinter artifacts
+#      - name: Archive production artifacts
+#        if: ${{ success() }} || ${{ failure() }}
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: MegaLinter reports
+#          path: |
+#            megalinter-reports
+#            mega-linter.log
+#            linter-helps.json
+#            linter-versions.json
+#
+#      - name: debug
+#        if: ${{ success() }} || ${{ failure() }}
+#        run: echo ${{ steps.docker_build.outcome }}
+#
+#      # Test mega-linter-runner with newly created image
+#      - name: Setup Node
+#        if: ${{ steps.docker_build.outcome }} == 'success' && !contains(github.event.head_commit.message, 'quick build')
+#        uses: actions/setup-node@v3.7.0
+#        with:
+#          node-version: "12"
+#      - name: Install NPM dependencies
+#        if: ${{ steps.docker_build.outcome }} == 'success' && !contains(github.event.head_commit.message, 'quick build')
+#        run: cd mega-linter-runner && sudo yarn install --frozen-lockfile && sudo npm link
+#      - name: Run mega-linter-runner tests
+#        if: ${{ steps.docker_build.outcome }} == 'success' && !contains(github.event.head_commit.message, 'quick build')
+#        run: cd mega-linter-runner && MEGALINTER_RELEASE=${{ steps.image_tag.outputs.tag }} MEGALINTER_NO_DOCKER_PULL=true npm run test
+#
+#      ##############################################
+#      # Check Docker image security with Trivy #
+#      ##############################################
+#
+#      - name: Run Trivy vulnerability scanner
+#        uses: aquasecurity/trivy-action@master
+#        with:
+#          image-ref: "docker.io/oxsecurity/megalinter:${{ steps.image_tag.outputs.tag }}"
+#          format: 'table'
+#          exit-code: '1'
+#          ignore-unfixed: true
+#          scanners: vuln
+#          vuln-type: 'os,library'
+#          severity: 'CRITICAL,HIGH'
+#          timeout: 15m0s
